// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KennethScott.AddDbUpFile
{
    static class Vsix
    {
        public const string Id = "A51A65E3-D01F-479E-BE1E-8B3FC7136CEB";
        public const string Name = "Add DbUp File";
        public const string Description = @"The fastest and easiest way to add a DbUp file to any project";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Kenneth Scott";
        public const string Tags = "file, add, template, dbup";
    }
}
